version: '3.8'

services:
  frontend-server:
    image: ${DOCKER_REGISTRY-}frontend.server
    build:
      context: .
      dockerfile: AKS.Three.Tier.App.Frontend/Server/Dockerfile
    environment:
      - API_URL=http://api
    ports:
      - "5100:80"
    depends_on:
      - api

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: AKS.Three.Tier.App.API/Dockerfile
    environment:
      - REDIS_CONNECTIONSTRING=redis
    ports:
      - "5101:80"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"